import './global.css';

export const metadata = {
    title: 'Welcome to production',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>{children}</body>
            <h1>lorem</h1>
        </html>
    );
}
